### ISSUE TITLE
Speak Touch touch exploration crash

### ISSUE THREAD

**Issue by Irineu333** [Irineu333/SpeakTouch#18]
Speak Touch is crashing during touch exploration.

**Comment by Irineu333** [comment]
I reproduced the error, which occurred while trying to load a class from the old support library.

```
FATAL EXCEPTION: main
  Process: com.neo.speaktouch, PID: 23306
  java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
   at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:502)
   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
  Caused by: java.lang.reflect.InvocationTargetException
   at java.lang.reflect.Method.invoke(Native Method)
   at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930) 
  Caused by: java.lang.ClassNotFoundException: android.support.v7.widget.RecyclerView
   at java.lang.Class.classForName(Native Method)
   at java.lang.Class.forName(Class.java:454)
   at java.lang.Class.forName(Class.java:379)
   at com.neo.speaktouch.utils.extensions.CharSequenceKt.instanceOf(CharSequence.kt:18)
   at com.neo.speaktouch.model.Type$Companion.get(Type.kt:28)
   at com.neo.speaktouch.intercepter.SpeechInterceptor.getType(SpeechInterceptor.kt:52)
   at com.neo.speaktouch.intercepter.SpeechInterceptor.getContent(SpeechInterceptor.kt:97)
   at com.neo.speaktouch.intercepter.SpeechInterceptor.speak(SpeechInterceptor.kt:36)
   at com.neo.speaktouch.intercepter.SpeechInterceptor.handler(SpeechInterceptor.kt:19)
   at com.neo.speaktouch.service.SpeakTouchService.onAccessibilityEvent(SpeakTouchService.kt:27)
   at android.accessibilityservice.AccessibilityService$2.onAccessibilityEvent(AccessibilityService.java:1635)
   at android.accessibilityservice.AccessibilityService$IAccessibilityServiceClientWrapper.executeMessage(AccessibilityService.java:1824)
   at com.android.internal.os.HandlerCaller$MyHandler.handleMessage(HandlerCaller.java:44)
   at android.os.Handler.dispatchMessage(Handler.java:107)
   at android.os.Looper.loop(Looper.java:214)
   at android.app.ActivityThread.main(ActivityThread.java:7356)
   at java.lang.reflect.Method.invoke(Native Method) 
   at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492) 
   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930) 
  Caused by: java.lang.ClassNotFoundException: Didn't find class "android.support.v7.widget.RecyclerView" on path: DexPathList[[zip file "/data/app/com.neo.speaktouch-Kxi2LR3L2xvwPvmhWxe7SA==/base.apk"],nativeLibraryDirectories=[/data/app/com.neo.speaktouch-Kxi2LR3L2xvwPvmhWxe7SA==/lib/x86, /system/lib, /system/product/lib]]
   at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:196)
   at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
   at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
   at java.lang.Class.classForName(Native Method) 
   at java.lang.Class.forName(Class.java:454) 
   at java.lang.Class.forName(Class.java:379) 
   at com.neo.speaktouch.utils.extensions.CharSequenceKt.instanceOf(CharSequence.kt:18) 
   at com.neo.speaktouch.model.Type$Companion.get(Type.kt:28) 
   at com.neo.speaktouch.intercepter.SpeechInterceptor.getType(SpeechInterceptor.kt:52) 
   at com.neo.speaktouch.intercepter.SpeechInterceptor.getContent(SpeechInterceptor.kt:97) 
   at com.neo.speaktouch.intercepter.SpeechInterceptor.speak(SpeechInterceptor.kt:36) 
   at com.neo.speaktouch.intercepter.SpeechInterceptor.handler(SpeechInterceptor.kt:19) 
   at com.neo.speaktouch.service.SpeakTouchService.onAccessibilityEvent(SpeakTouchService.kt:27) 
   at android.accessibilityservice.AccessibilityService$2.onAccessibilityEvent(AccessibilityService.java:1635) 
   at android.accessibilityservice.AccessibilityService$IAccessibilityServiceClientWrapper.executeMessage(AccessibilityService.java:1824) 
   at com.android.internal.os.HandlerCaller$MyHandler.handleMessage(HandlerCaller.java:44) 
   at android.os.Handler.dispatchMessage(Handler.java:107) 
   at android.os.Looper.loop(Looper.java:214) 
   at android.app.ActivityThread.main(ActivityThread.java:7356) 
   at java.lang.reflect.Method.invoke(Native Method) 
   at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492) 
   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930) 
```
Origin:
![image](https://user-images.githubusercontent.com/45833588/224424348-21c523ba-56c5-4a63-8a9a-ddfca0fc6281.png)

**Comment by Irineu333** [comment]
It was my mistake not to handle the `ClassNotFoundException`. While studying TalkBack, I found out that it also can't load widgets from the support library, so there's probably nothing that can be done about it. Knowing this, it's best for type detection to depend as little as possible on inheritance detection.

Talkback

![image](https://user-images.githubusercontent.com/45833588/224433520-93c94e34-40d0-4dea-b275-349a4f6ca2b5.png)
